// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mvnEstatLocal
double mvnEstatLocal(NumericMatrix y);
RcppExport SEXP _BrownCondInd_mvnEstatLocal(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(mvnEstatLocal(y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BrownCondInd_mvnEstatLocal", (DL_FUNC) &_BrownCondInd_mvnEstatLocal, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BrownCondInd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
